version: '3.9'

services:
  backend:
    build: ./lead_gen_api
    volumes:
      - ./lead_gen_api:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: leadGen-frontend/Dockerfile
    ports:
      - "3000:80"  # Maps container's port 80 (Nginx) to localhost:3000
    restart: always

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${AWS_RDS_PASSWORD}

volumes:
  postgres_data:
