# Generated by Django 5.2 on 2025-04-21 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findLeads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadtable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
