name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EBS_APP_NAME: ${{ secrets.EBS_APP_NAME }}
      EBS_ENV_NAME: ${{ secrets.EBS_ENV_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Python and EB CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip install awsebcli --upgrade
          eb --version

      - name: Initialize EB CLI
        run: |
          eb init "$EBS_APP_NAME" \
            --platform "Docker running on 64bit Amazon Linux 2" \
            --region "$AWS_REGION"

      - name: Deploy to EB
        run: |
          eb use "$EBS_ENV_NAME"
          eb deploy --staged --label "v-${{ github.run_number }}"
