jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip source bundle
        run: |
          zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "$EBS_APP_NAME" \
            --version-label "v-${{ github.run_number }}" \
            --source-bundle S3Bucket=$EBS_APP_NAME, S3Key="deploy/v-${{ github.run_number }}.zip"

          aws elasticbeanstalk update-environment \
            --application-name "$EBS_APP_NAME" \
            --environment-name "$EBS_ENV_NAME" \
            --version-label "v-${{ github.run_number }}"
