name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and Deploy to AWS EB
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EBS_APP_NAME: ${{ secrets.EBS_APP_NAME }}
      EBS_ENV_NAME: ${{ secrets.EBS_ENV_NAME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python & Pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Install AWS EB CLI
        run: |
          pip3 install --upgrade pip
          pip3 install awsebcli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize EB CLI
        run: |
          eb init "${{ env.EBS_APP_NAME }}" \
            --platform "Docker running on 64bit Amazon Linux 2" \
            --region "${{ env.AWS_REGION }}"

      - name: Set EB Environment
        run: eb use "${{ env.EBS_ENV_NAME }}"

      - name: Zip Docker Compose App
        run: zip -r deploy.zip docker-compose.yml lead_gen_api leadGen-frontend

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy --staged --label "v-${{ github.run_number }}"
